import OpenAI from 'openai';
import { createOpenAIClient, MODEL } from '../config/openai';
import {
  EditorialProfile,
  ScriptReviewRequest,
  ScriptReviewResponse,
  AgentConfig,
} from '../types/agents';

export class ScriptReviewer {
  private openai: OpenAI;
  private model: string;
  private static instance: ScriptReviewer;

  private constructor(config: AgentConfig) {
    this.openai = createOpenAIClient();
    this.model = config.model;
  }

  public static getInstance(
    config: AgentConfig = { model: MODEL }
  ): ScriptReviewer {
    if (!ScriptReviewer.instance) {
      ScriptReviewer.instance = new ScriptReviewer(config);
    }
    return ScriptReviewer.instance;
  }

  async review(request: ScriptReviewRequest): Promise<ScriptReviewResponse> {
    try {
      console.log('🔍 Starting script review...');

      const completion = await this.openai.chat.completions.create({
        model: this.model,
        messages: [
          {
            role: 'system',
            content: `You are a script review agent in a creative automation pipeline.
Your task is to review, correct, and validate scripts generated for TikTok-style videos.
These scripts are written by another AI agent and intended to be converted into voiceovers using ElevenLabs TTS.
You are not generating the script. You are verifying and adjusting it to match:
	1.	The creator's editorial profile
	2.	The guidelines for TTS compatibility
	3.	The clarity and flow needed for short-form, spoken content

⸻

🧩 INPUT YOU RECEIVE

You receive a JSON object that includes:
	•	script: the script generated by a previous agent
	•	editorial_profile: a block of text with info like tone, style, persona, examples to avoid, writing preferences
	•	video_context (optional): tags or metadata from video clips provided by the creator
	•	prompt_intention: a user prompt or instruction summarizing the video's message/goal

⸻

🛠️ YOUR ROLE

Your job is to audit and fix the script to ensure it:
	1.	Reflects the creator's style: tone, rhythm, and narrative preferences
	2.	Matches the original intent of the video prompt
	3.	Is optimized for voice generation by ElevenLabs
	4.	Flows naturally when read aloud

⸻

🗣️ VOICEOVER SANITIZATION RULES

Ensure the script is compatible with ElevenLabs voice synthesis:
	•	Avoid symbols like *, /, (), [], emojis, or markdown
	•	Remove or replace all textual stage directions (e.g. "[pause]", "(laughs)")
	•	Avoid all caps unless the creator's style requires shouting
	•	Punctuate properly: use . , ! ? — no ellipses …, slashes /, or pipes |
	•	Avoid long, nested, or convoluted sentences
	•	Avoid abbreviations unless phonetically readable (e.g. "AI" is fine, "w/" is not)

⸻

⚠️ FLAG IF
	•	The script deviates from the creator's editorial profile
	•	It contains filler, clichés, vague phrases, or breaks clarity
	•	It's over 60 seconds when read aloud (~110–130 words max)
	•	It includes tech terms that aren't explained or simplified

⸻

🎯 YOUR GOAL

Return the script with improvements if needed, or as is.
Do not provide comments in any shape of form, only the script ready to be spoken.
Ensure the script is smooth, clean, and ready for ElevenLabs synthesis without manual intervention.

Editorial Profile:
- Persona: ${request.editorialProfile.persona_description}
- Tone: ${request.editorialProfile.tone_of_voice}
- Audience: ${request.editorialProfile.audience}
- Style: ${request.editorialProfile.style_notes}
`,
          },
          {
            role: 'user',
            content: `
            System Prompt from the user:
            ${request.userSystemPrompt}

            Script created from the user prompt by the script generator:
            ${request.script}
            `,
          },
        ],
      });

      const reviewedScript = completion.choices[0]?.message?.content;
      if (!reviewedScript) {
        throw new Error('Failed to review script: Empty response');
      }

      // Validate script length
      const wordCount = reviewedScript.split(/\s+/).length;
      const estimatedDuration = wordCount * 0.4; // Rough estimate: 0.4 seconds per word

      const warnings: string[] = [];

      if (estimatedDuration < 30 || estimatedDuration > 60) {
        warnings.push(
          `Script duration: Estimated ${estimatedDuration.toFixed(1)} seconds`
        );
      }

      // Check for common issues
      const hasStageDirections = /[\[\(].*?[\]\)]/.test(reviewedScript);
      const hasInvalidPunctuation = /[…|\/]/.test(reviewedScript);
      const hasLongSentences = reviewedScript
        .split(/[.!?]/)
        .some((sentence) => sentence.split(/\s+/).length > 25);

      if (hasStageDirections) {
        warnings.push('Script contains stage directions that may affect TTS');
      }
      if (hasInvalidPunctuation) {
        warnings.push('Script contains invalid punctuation for TTS');
      }
      if (hasLongSentences) {
        warnings.push('Script contains sentences that may be too long for TTS');
      }

      if (warnings.length > 0) {
        console.warn('⚠️ Script review warnings:', warnings);
      }

      console.log(
        `✅ Script reviewed: ${wordCount} words, ~${estimatedDuration.toFixed(
          1
        )}s`
      );

      return {
        reviewedScript,
        estimatedDuration,
        wordCount,
        warnings: warnings.length > 0 ? warnings : undefined,
      };
    } catch (error) {
      console.error('❌ Error reviewing script:', error);
      throw new Error(
        `Failed to review script: ${
          error instanceof Error ? error.message : 'Unknown error'
        }`
      );
    }
  }
}
